### ISSUE TITLE
No device detected. 

### ISSUE THREAD

**Issue by oriolism** [jorticus/pymate#21]
Hi, Im trying to make pyMate work with my Flexmax 80 connected to a Raspberry Pi Model B+ with the adapter. This is how a have the adapter connected:

https://drive.google.com/file/d/1-ZQu4gvGehKYEoXtyyE8dvpHIVXu76rx/view?usp=sharing

When i run the scan.py or the readout.py file the Flexmax is not detected. Im using /dev/ttyAMA0 as the serial port, Octocopler chip is EL817 and my system is 24V. The raspberry pi is running Raspbian Strech with pyserial installed and the serial port is enabled on the settings. As part of the troubleshoot i change the Tx and Rx pin on both side (Rpi and Flexmax) . Are these values for the resistor correct for this chip? Any recommendation? Thanks!

**Comment by jorticus** [comment]
I can't access your link.

If you have access to an oscilloscope or logic analyzer, that would be very helpful and would allow you to see whether optocoupler is working as expected. The resistor values aren't critical, somewhere in the range of 400ohm - 2kohm probably makes sense.

On the software side you can enable extra debug logs, which may help figure out what's going wrong. Add the following to your script:
```
import logging
log = logging.getLogger('mate')
log.setLevel(logging.DEBUG)
log.addHandler(logging.StreamHandler())
```
Then send me the logs emitted when you try to scan.

**Comment by oriolism** [comment]
![pymate](https://user-images.githubusercontent.com/22877411/93717048-3773bf80-fb41-11ea-80a6-f7a6d8a9a7a7.png)

Unfortunately I don't have an oscilloscope or logic analyzer. 

Here's the log. 

pi@pyMate:~/pymate$ sudo python scan.py   
MATE Bus Scan
Send [Port0, Type=0x02, Addr=0x0000, Param=0x0000]
TX: [1] 00
TX: [0] 02 00 00 00 00 00 02
RETRY
TX: [1] 00
TX: [0] 02 00 00 00 00 00 02
RETRY
TX: [1] 00
TX: [0] 02 00 00 00 00 00 02
RETRY
No device connected!

Thanks!

**Comment by jorticus** [comment]
Ok logs don't indicate much except that there is no communication happening.

Do you have a multimeter? Can you confirm that there is 24V between Green & Green/White? 
There are two standards of RJ45 wire colouring (EIA 568-A & EIA 568-B), and these swap the green/orange pairs for some reason.

As for the data lines, the striped wire (Pin 3, either Orange/White or Green/White) should go to the RPi's RX pin. The solid colour wire (Pin 6) should go to the RPi's TX pin. Ie, **RX->TX**, not **TX->TX**. 

You could try bumping up the 510R resistor to **100R** (LED current from 3mA to 20mA) since you are operating on a 3.3V supply.

_EDIT:_
I now see that your RPi's RXD pin is connected to TX on the green board. Try connecting it to TXD instead. TXD on the RPi is an output and should drive the optocoupler LED on pin 1&2 via the 510/100R resistor. The other side of the optocoupler should then be connected to the MX's RX line (Solid colour wire, Pin 6)
