### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by Julien00859** [jorticus/pymate#29]
Hello there,

Python 2 is end of life since a couple of years now. Actually according to the commit dates, the project began in 2016, a time where it was already discouraged to begin new projects using Python 2. Today a student did show in a group chat asking for assistance to install this library on a py3-only-system, apparently his teacher cares as much as you do about software maintenance and security.

Please upgrade this lib to python3 or archive it. If you want to keep py2 backward compatibility you can learn about the "six" library.

**Comment by jorticus** [comment]
Hey, I am well aware Python 2 is out of support, and actually I have been working on Python 3 support in a separate branch ([feature/python3](/jorticus/pymate/tree/feature/python3)) which several people have tried out already. Please try this branch and let me know how it goes.

The reason I chose Python 2 to start with despite being not recommended was due to limitations in the hardware I chose (The linux-based Carambola2), which was very cheap and very low power, but unfortunately did not support Python 3. You will be shocked at how out of date and unmaintained a lot of real-world embedded hardware is!

Like most open source projects, I don't get paid for this work, and can only contribute to it when time allows. You are of course welcome to contribute to the project yourself...
